[package]
name = "ferry"
version = "0.2.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
ignore = "0.4"
suppaftp = "6"
rpassword = "7"
lsp-server = "0.8"
lsp-types = "0.97"
percent-encoding = "2"
tempfile = "3"
fs2 = "0.4"

[dev-dependencies]
testcontainers = { version = "0.20", features = ["blocking"] }

[[bin]]
name = "ferry"
path = "src/main.rs"

[[bin]]
name = "ferry-lsp"
path = "src/bin/ferry-lsp.rs"

[lib]
name = "ferry"
path = "src/lib.rs"
